[package]
exclude = [
	".babelrc",
	"bower.json",
	".bowerrc",
	"/build",
	"composer.json",
	"docs",
	".drone.yml",
	".editorconfig",
	".eslintignore",
	".eslintrc.yml",
	".git",
	".gitattributes",
	".github",
	".gitignore",
	".jscsrc",
	".jshintrc",
	".jshintignore",
	".l10nignore",
	"js/tests",
	"karma.conf.js",
	"l10n/no-php",
	".tx",
	"Makefile",
	"node_modules",
	"package.json",
	"phpunit*xml",
	"README.md",
	"run-*lint.sh",
	".scrutinizer.yml",
	".stylelintrc",
	"/src",
	"tests",
	".travis.yml",
	"webpack.*.js"
]

before_cmds = [
 	"make clean",
	"make clean-dev",
	"make npm-init",
	"make build-js-production",
	"make create-tag"
]
